// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application struct.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permissions$0 from "./internal/permissions/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs empties the diagnostic log.
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(1566804265);
}

/**
 * CopyToClipboard puts text on the system clipboard.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyToClipboard(text) {
    return $Call.ByID(1438304177, text);
}

/**
 * DeleteAPIKey removes an API key from the OS keychain.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAPIKey(key) {
    return $Call.ByID(3581779133, key);
}

/**
 * GetConfig returns the current configuration.
 * @returns {$CancellablePromise<$models.ConfigResponse>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDictionary returns the current dictionary words.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDictionary() {
    return $Call.ByID(3258138775).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetEntryAudio returns the stored recording for an entry.
 * @param {string} id
 * @returns {$CancellablePromise<$models.AudioData>}
 */
export function GetEntryAudio(id) {
    return $Call.ByID(297988749, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetHistory returns the dictation history, newest first.
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetHistory() {
    return $Call.ByID(210907985).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHistoryInfo returns the retention settings and current disk usage.
 * @returns {$CancellablePromise<$models.HistoryInfo>}
 */
export function GetHistoryInfo() {
    return $Call.ByID(544859081).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLogs returns the diagnostic log, newest first.
 * @returns {$CancellablePromise<$models.LogRecord[]>}
 */
export function GetLogs() {
    return $Call.ByID(1743981476).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetPermissions returns the current system permission status.
 * @returns {$CancellablePromise<permissions$0.Status>}
 */
export function GetPermissions() {
    return $Call.ByID(2898822425).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetSnippets returns the current snippets.
 * @returns {$CancellablePromise<config$0.Snippet[]>}
 */
export function GetSnippets() {
    return $Call.ByID(2651092597).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetStatus returns the current daemon status.
 * @returns {$CancellablePromise<$models.StatusResponse>}
 */
export function GetStatus() {
    return $Call.ByID(1043986649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetVersion returns the app version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * HasAPIKey checks if an API key exists.
 * @param {string} key
 * @returns {$CancellablePromise<boolean>}
 */
export function HasAPIKey(key) {
    return $Call.ByID(2818092688, key);
}

/**
 * OpenAccessibilitySettings opens the OS accessibility settings panel.
 * @returns {$CancellablePromise<void>}
 */
export function OpenAccessibilitySettings() {
    return $Call.ByID(2298907446);
}

/**
 * OpenMicrophoneSettings opens the OS microphone privacy settings panel.
 * @returns {$CancellablePromise<void>}
 */
export function OpenMicrophoneSettings() {
    return $Call.ByID(2078724176);
}

/**
 * RetryEntry transcribes a stored recording again and updates its history entry.
 * When toClipboard is true the recovered text is also copied.
 * 
 * Delivery is deliberately limited to the clipboard: a retry is triggered from
 * the vox window, so that window holds the keyboard focus and typing the text
 * at "the cursor" would type it into vox itself.
 * 
 * This is the recovery path for a failed attempt — the spoken words are read
 * back from the kept recording instead of being spoken again.
 * @param {string} id
 * @param {boolean} toClipboard
 * @returns {$CancellablePromise<$models.RetryResult>}
 */
export function RetryEntry(id, toClipboard) {
    return $Call.ByID(3466209775, id, toClipboard).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * RevealEntryAudio shows a stored recording in the file manager.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RevealEntryAudio(id) {
    return $Call.ByID(3069195702, id);
}

/**
 * RevealHistoryFile shows history.jsonl in the file manager. Revealing rather
 * than opening it: .jsonl usually has no registered handler, so "open" would
 * either fail or launch something unexpected.
 * @returns {$CancellablePromise<void>}
 */
export function RevealHistoryFile() {
    return $Call.ByID(3113253382);
}

/**
 * SaveConfig updates and persists the configuration.
 * @param {$models.ConfigResponse} update
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(update) {
    return $Call.ByID(3442292638, update);
}

/**
 * SaveDictionary saves the dictionary and reloads.
 * @param {string[]} words
 * @returns {$CancellablePromise<void>}
 */
export function SaveDictionary(words) {
    return $Call.ByID(3950354708, words);
}

/**
 * SaveSnippets saves snippets and reloads.
 * @param {config$0.Snippet[]} snippets
 * @returns {$CancellablePromise<void>}
 */
export function SaveSnippets(snippets) {
    return $Call.ByID(3135394354, snippets);
}

/**
 * SetAPIKey stores an API key in the OS keychain.
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIKey(key, value) {
    return $Call.ByID(4066338368, key, value);
}

/**
 * ShowWindow brings the settings window to front.
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * Shutdown cleans up resources.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2987688963);
}

/**
 * Start initializes the app (hotkey listener, dynamic data).
 * Called by the desktop lifecycle (ServiceStartup) or headless entry.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1627660663);
}

/**
 * TestLLM tests the LLM backend connectivity.
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestLLM() {
    return $Call.ByID(2685437664).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * TestSTT tests the STT backend connectivity.
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestSTT() {
    return $Call.ByID(3485148538).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ConfigResponse.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.AudioData.createFrom;
const $$createType3 = $models.HistoryEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.HistoryInfo.createFrom;
const $$createType6 = $models.LogRecord.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = permissions$0.Status.createFrom;
const $$createType9 = config$0.Snippet.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.StatusResponse.createFrom;
const $$createType12 = $models.RetryResult.createFrom;
const $$createType13 = $models.TestResult.createFrom;
