// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application struct exposed to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permissions$0 from "./internal/permissions/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteAPIKey removes an API key from the OS keychain.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAPIKey(key) {
    return $Call.ByID(3581779133, key);
}

/**
 * GetConfig returns the current configuration.
 * @returns {$CancellablePromise<$models.ConfigResponse>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDictionary returns the current dictionary words.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDictionary() {
    return $Call.ByID(3258138775).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetHistory returns transcription history.
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetHistory() {
    return $Call.ByID(210907985).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPermissions returns the current system permission status.
 * @returns {$CancellablePromise<permissions$0.Status>}
 */
export function GetPermissions() {
    return $Call.ByID(2898822425).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSnippets returns the current snippets.
 * @returns {$CancellablePromise<config$0.Snippet[]>}
 */
export function GetSnippets() {
    return $Call.ByID(2651092597).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetStatus returns the current daemon status.
 * @returns {$CancellablePromise<$models.StatusResponse>}
 */
export function GetStatus() {
    return $Call.ByID(1043986649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetVersion returns the app version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * HasAPIKey checks if an API key exists.
 * @param {string} key
 * @returns {$CancellablePromise<boolean>}
 */
export function HasAPIKey(key) {
    return $Call.ByID(2818092688, key);
}

/**
 * OpenAccessibilitySettings opens the OS accessibility settings panel.
 * @returns {$CancellablePromise<void>}
 */
export function OpenAccessibilitySettings() {
    return $Call.ByID(2298907446);
}

/**
 * OpenMicrophoneSettings opens the OS microphone privacy settings panel.
 * @returns {$CancellablePromise<void>}
 */
export function OpenMicrophoneSettings() {
    return $Call.ByID(2078724176);
}

/**
 * SaveConfig updates and persists the configuration.
 * @param {$models.ConfigResponse} update
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(update) {
    return $Call.ByID(3442292638, update);
}

/**
 * SaveDictionary saves the dictionary and reloads.
 * @param {string[]} words
 * @returns {$CancellablePromise<void>}
 */
export function SaveDictionary(words) {
    return $Call.ByID(3950354708, words);
}

/**
 * SaveSnippets saves snippets and reloads.
 * @param {config$0.Snippet[]} snippets
 * @returns {$CancellablePromise<void>}
 */
export function SaveSnippets(snippets) {
    return $Call.ByID(3135394354, snippets);
}

/**
 * SetAPIKey stores an API key in the OS keychain.
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIKey(key, value) {
    return $Call.ByID(4066338368, key, value);
}

/**
 * ShowWindow brings the settings window to front.
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * TestLLM tests the LLM backend connectivity.
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestLLM() {
    return $Call.ByID(2685437664).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * TestSTT tests the STT backend connectivity.
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestSTT() {
    return $Call.ByID(3485148538).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ConfigResponse.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.HistoryEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = permissions$0.Status.createFrom;
const $$createType5 = config$0.Snippet.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.StatusResponse.createFrom;
const $$createType8 = $models.TestResult.createFrom;
