// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigResponse holds the config for the frontend.
 */
export class ConfigResponse {
    /**
     * Creates a new ConfigResponse instance.
     * @param {Partial<ConfigResponse>} [$$source = {}] - The source object to create the ConfigResponse.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["raw"] = false;
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("handsfree_timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handsfree_timeout"] = 0;
        }
        if (!("doubletap_window" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doubletap_window"] = 0;
        }
        if (!("notifications" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notifications"] = false;
        }
        if (!("audio_feedback" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["audio_feedback"] = false;
        }
        if (!("show_overlay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["show_overlay"] = false;
        }
        if (!("stt_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stt_backend"] = "";
        }
        if (!("stt_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stt_url"] = "";
        }
        if (!("llm_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_backend"] = "";
        }
        if (!("llm_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_url"] = "";
        }
        if (!("llm_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigResponse(/** @type {Partial<ConfigResponse>} */($$parsedSource));
    }
}

/**
 * HistoryEntry is a frontend-friendly history entry.
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("raw_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw_text"] = "";
        }
        if (!("cleaned_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cleaned_text"] = "";
        }
        if (!("app_context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_context"] = "";
        }
        if (!("duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_seconds"] = 0;
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

/**
 * StatusResponse holds status info for the frontend.
 */
export class StatusResponse {
    /**
     * Creates a new StatusResponse instance.
     * @param {Partial<StatusResponse>} [$$source = {}] - The source object to create the StatusResponse.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("has_key" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusResponse(/** @type {Partial<StatusResponse>} */($$parsedSource));
    }
}

/**
 * TestResult holds the result of a backend test.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}
