// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AudioData carries a recording to the frontend as base64, so it can be played
 * or downloaded from the history view.
 */
export class AudioData {
    /**
     * Creates a new AudioData instance.
     * @param {Partial<AudioData>} [$$source = {}] - The source object to create the AudioData.
     */
    constructor($$source = {}) {
        if (!("base64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base64"] = "";
        }
        if (!("mime_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mime_type"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AudioData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioData(/** @type {Partial<AudioData>} */($$parsedSource));
    }
}

/**
 * ConfigResponse holds the config for the frontend.
 */
export class ConfigResponse {
    /**
     * Creates a new ConfigResponse instance.
     * @param {Partial<ConfigResponse>} [$$source = {}] - The source object to create the ConfigResponse.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["raw"] = false;
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("handsfree_timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handsfree_timeout"] = 0;
        }
        if (!("doubletap_window" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doubletap_window"] = 0;
        }
        if (!("notifications" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notifications"] = false;
        }
        if (!("audio_feedback" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["audio_feedback"] = false;
        }
        if (!("show_overlay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["show_overlay"] = false;
        }
        if (!("stt_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stt_backend"] = "";
        }
        if (!("stt_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stt_url"] = "";
        }
        if (!("llm_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_backend"] = "";
        }
        if (!("llm_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_url"] = "";
        }
        if (!("llm_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigResponse(/** @type {Partial<ConfigResponse>} */($$parsedSource));
    }
}

/**
 * HistoryEntry is a frontend-friendly history entry.
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("raw_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw_text"] = "";
        }
        if (!("cleaned_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cleaned_text"] = "";
        }
        if (!("app_context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_context"] = "";
        }
        if (!("duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_seconds"] = 0;
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("failed_step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["failed_step"] = "";
        }
        if (!("error_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_message"] = "";
        }
        if (!("suspected_hallucination" in $$source)) {
            /**
             * SuspectedHallucination flags a transcript that matched a known Whisper-
             * hallucination pattern. The text was delivered and stored regardless; the
             * flag tells the user to double-check it.
             * @member
             * @type {boolean}
             */
            this["suspected_hallucination"] = false;
        }
        if (!("has_audio" in $$source)) {
            /**
             * HasAudio reports whether the recording is still on disk. Audio is kept
             * for the newest entries only, so this is false for most of the history.
             * @member
             * @type {boolean}
             */
            this["has_audio"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

/**
 * HistoryInfo describes what the history keeps and what that costs on disk.
 */
export class HistoryInfo {
    /**
     * Creates a new HistoryInfo instance.
     * @param {Partial<HistoryInfo>} [$$source = {}] - The source object to create the HistoryInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("text_kept" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["text_kept"] = 0;
        }
        if (!("audio_kept" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["audio_kept"] = 0;
        }
        if (!("audio_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["audio_files"] = 0;
        }
        if (!("audio_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["audio_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * UsageError is set when the recordings directory could not be read, so the
             * UI can say "unknown" instead of showing a confident zero.
             * @member
             * @type {string | undefined}
             */
            this["usage_error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryInfo(/** @type {Partial<HistoryInfo>} */($$parsedSource));
    }
}

/**
 * LogRecord is a frontend-friendly diagnostic record.
 */
export class LogRecord {
    /**
     * Creates a new LogRecord instance.
     * @param {Partial<LogRecord>} [$$source = {}] - The source object to create the LogRecord.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogRecord(/** @type {Partial<LogRecord>} */($$parsedSource));
    }
}

/**
 * RetryResult reports the outcome of a second transcription attempt.
 * 
 * OK covers the transcription only. Delivery to the clipboard is reported
 * separately, because a recovered text that could not be copied must not look
 * like a success — the user would try to paste nothing.
 */
export class RetryResult {
    /**
     * Creates a new RetryResult instance.
     * @param {Partial<RetryResult>} [$$source = {}] - The source object to create the RetryResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("delivered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["delivered"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["delivery_error"] = undefined;
        }
        if (!("persisted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["persisted"] = false;
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {HistoryEntry}
             */
            this["entry"] = (new HistoryEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RetryResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField5_0($$parsedSource["entry"]);
        }
        return new RetryResult(/** @type {Partial<RetryResult>} */($$parsedSource));
    }
}

/**
 * StatusResponse holds status info for the frontend.
 */
export class StatusResponse {
    /**
     * Creates a new StatusResponse instance.
     * @param {Partial<StatusResponse>} [$$source = {}] - The source object to create the StatusResponse.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("has_key" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusResponse(/** @type {Partial<StatusResponse>} */($$parsedSource));
    }
}

/**
 * TestResult holds the result of a backend test.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HistoryEntry.createFrom;
